author ="Whatever"
baseURL="https://oldbig9.github.io/"
title  ="什么阿猫阿狗的"

# 全局配置
defaultContentLanguage="zh-cn"
summaryLength         =30
hasCJKLanguage        =true
enableRobotsTXT       =false

[sitemap]
  changefreq='daily'
  filename  ='sitemap.xml'
  priority  =0.5

[outputs]
  home=["HTML", "RSS", "JSON"]
