[[main]]
  identifier="Docs"
  name      ="技术"
  pageRef   ="/categories/tech"
  weight    =1
  # 下拉子菜单
  [[main]]
    name = "golang"
    parent = "Docs"
    pageRef = "/docs/go"
    weight = 1
  [[main]]
    name = "grpc"
    parent = "Docs"
    pageRef = "/docs/grpc"
    weight = 1
  [[main]]
    name = "protobuf"
    parent = "Docs"
    pageRef = "/docs/protobuf"
    weight = 1

[[main]]
  identifier="Songci"
  name      ="宋词"
  pageRef   ="/songci"
  weight    =2

[[main]]
  identifier="Note"
  name      ="日志"
  pageRef   ="/note"
  weight    =3

[[main]]
  identifier="tags"
  name      ="标签"
  pageRef   ="/tags"
  weight    =4

[[main]]
  identifier="linqianxi"
  pre       ="link"
  name      ="林浅喜"
  url       ="https://space.bilibili.com/430967976" # 外部链接
  weight    =10


