colorScheme = "ocean" # blowfish (default), avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, andslate.
defaultBackgroundImage = "/img/paint.jpg"
defaultAppearance = "light"
enableCodeCopy = true
enableSearch = true
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true
dateFormat = "2006-01-02"

[homepage]
  layout = "background" #  Valid values are page, profile, hero, card, background, custom
  layoutBackgroundBlur = true
  homepageImage = "/img/paint.jpg"
  showRecent = true
  showRecentItems = 3

[author]
  name = "什么阿猫阿狗的"
  image = "img/cat.png"
  headline = "我有一片果园，自由却孤独地活着 - [林浅喜](https://space.bilibili.com/430967976)"

[header]
  layout = "fixed-fill-blur" #  basic, fixed, fixed-fill, and fixed-fill-blur.

[list]
  showSummary = true
  constrainItemsWidth = true
  showCards = false
  groupByYear = false
  showHero = true
  heroStyle = "background"

[article]
  showTableOfContents = true
  showHero = true
  heroStyle = "background"
  showReadingTime = false
  seriesOpened = true
  showAuthor = false
  showTaxonomies = true
[taxonomy]
  showHero = true
  heroStyle = "background"
[term]
  showHero = true
  heroStyle = "background"
